
- name: Configuration deployment
  hosts: FABRIC # <-- Targeted devices
  connection: local
  gather_facts: false
  tasks:
    - name: Deploy configurations and tags to CloudVision
      ansible.builtin.import_role:
        name: arista.avd.cv_deploy
      vars:
        cv_server: 192.168.0.5
        cv_token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJkaWQiOjc2NjI2OTcwOTYwNTg3NjU2MjEsImRzbiI6ImF2ZCIsImRzdCI6ImFjY291bnQiLCJleHAiOjE3ODQyOTY3OTksImlhdCI6MTc4NDE3NTk1Nywib2dpIjozLCJvZ24iOiJEZWZhdWx0Iiwic2lkIjoiMmZlYzBiNGJiMzYzM2MwNmEyZmFmNzE2ODBiYjE2YmI0OTVkYzc5OTY3Yzc2Yzk2ZjkzYTZjMjQwNTgyM2E0My1TN3owbzJYUVFMOThzZEVmZUt2MFhsNzgxOG42alNETkdrZENWLWxRIn0.JKyJ705i5UrfuWGiRjrjuG5fS1hyscbYtFlZxU9oZ-JwjUOcpkOR1IHAjJcy4uDXUIhsw5ly6jjQFnHmu_7YAQdn6EFUsBlMYmemOqAijGwvRLv8CNa2DS9DioELoyJZ6fyTBaLZ1N6XhKLLuMfRQkUBNq9m7ifcuOxrIS157NoxkL798N4C_4bZ1m6G58rUfo3mhRvx4nLOXHUPwNlATvfuMqwoam2zrvVy578AuuSXq87RvN7L1W2qXiuitvdPhOltCeK4-gUE672V9lC0xMSJr-g4EfsrfKpBBvPHNNAUFx_JESYjDmHNkEckU8_GT5bd7e14xxzv_rz0GF6zNgsS6FrSbkGk3_vygFyZdTnNrE-PM0R4u-uA0hp2dyn4kHHtidkKcnOYoNZ3glDxL1_D9sOBMbAlhH6bCjbYSKwwCRlAZG23CpFz0inyk702__PmSwd9FfKwRtvS9zfHXxFXfg0YK1KlOhSEi5K2hT4VUKyNU6Fk2VBSsXOWR1zJ-pcHMCLdUS5d6mNpbOUDMaTiGMToO6bVOBoVT_nQon5BibEIvXW52Kt-WS4I9N8zEl9tP93LR7u9Cb5mstKBKjYQe7r8X6iqvEH2gsBix0mhLMu_jF3pW_bj3JU90pvwpZZ1-9iFAlqDn7pbOY63hiRH_RN9B8HOVEeHfBnSLcI
        cv_verify_certs: false
